version: '3.8'
services:
  backend:
    build:
      context: ./server
      dockerfile: dockerfile
    ports:
      - "8080:3000" # Replace with actual ports
    networks:
      - your-network

  frontend:
    build:
      context: ./client
      dockerfile: dockerfile
    ports:
      - "3001:3002" # Replace with actual ports
    networks:
      - your-network

networks:
  your-network:
    driver: bridge
